// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `file_backup_logic.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var Utils = require("utils").Utils;
    var Slice = Ice.Slice;

    var FileBackup = __M.module("FileBackup");

    FileBackup.Logic = Slice.defineObject(
        undefined,
        Ice.Object, undefined, 0,
        [
            "::FileBackup::Logic",
            "::Ice::Object"
        ],
        -1, undefined, undefined, false);

    FileBackup.LogicPrx = Slice.defineProxy(Ice.ObjectPrx, FileBackup.Logic.ice_staticId, undefined);

    Slice.defineOperations(FileBackup.Logic, FileBackup.LogicPrx,
    {
        "MountNas": [, , , , , , [[7]], , 
        [
            Utils.SystemError
        ], , ],
        "UmountNas": [, , , , , [1], [[7]], , 
        [
            Utils.SystemError
        ], , ],
        "MountBackup": [, , , , , , [[7]], , 
        [
            Utils.SystemError
        ], , ],
        "UmountBackup": [, , , , , , [[7]], , 
        [
            Utils.SystemError
        ], , ],
        "Backup": [, , , , , , [[7]], , 
        [
            Utils.SystemError
        ], , ],
        "CancleBackup": [, , , , , , [[7]], , 
        [
            Utils.SystemError
        ], , ],
        "QueryBackupStatus": [, , , , , [7], , , 
        [
            Utils.SystemError
        ], , ],
        "Shutdown": [, , , , , , , , , , ]
    });
    exports.FileBackup = FileBackup;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
