// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `CustomizedOS.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef ____cpp_3_5_CustomizedOS_h__
#define ____cpp_3_5_CustomizedOS_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <utils.h>
#include <Ice/Identity.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace CustomizedOS
{

class MiniLoader;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::CustomizedOS::MiniLoader>&);
::IceProxy::Ice::Object* upCast(::IceProxy::CustomizedOS::MiniLoader*);

class CallbackSender;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::CustomizedOS::CallbackSender>&);
::IceProxy::Ice::Object* upCast(::IceProxy::CustomizedOS::CallbackSender*);

}

}

namespace CustomizedOS
{

class MiniLoader;
bool operator==(const MiniLoader&, const MiniLoader&);
bool operator<(const MiniLoader&, const MiniLoader&);
::Ice::Object* upCast(::CustomizedOS::MiniLoader*);
typedef ::IceInternal::Handle< ::CustomizedOS::MiniLoader> MiniLoaderPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::CustomizedOS::MiniLoader> MiniLoaderPrx;
void __patch(MiniLoaderPtr&, const ::Ice::ObjectPtr&);

class CallbackSender;
bool operator==(const CallbackSender&, const CallbackSender&);
bool operator<(const CallbackSender&, const CallbackSender&);
::Ice::Object* upCast(::CustomizedOS::CallbackSender*);
typedef ::IceInternal::Handle< ::CustomizedOS::CallbackSender> CallbackSenderPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::CustomizedOS::CallbackSender> CallbackSenderPrx;
void __patch(CallbackSenderPtr&, const ::Ice::ObjectPtr&);

}

namespace CustomizedOS
{

typedef ::std::vector< ::Ice::Byte> BinaryStream;

}

namespace CustomizedOS
{

class Callback_MiniLoader_popen_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_MiniLoader_popen_Base> Callback_MiniLoader_popenPtr;

class Callback_MiniLoader_rwFile_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_MiniLoader_rwFile_Base> Callback_MiniLoader_rwFilePtr;

class Callback_MiniLoader_getRunPath_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_MiniLoader_getRunPath_Base> Callback_MiniLoader_getRunPathPtr;

class Callback_CallbackSender_addClient_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_CallbackSender_addClient_Base> Callback_CallbackSender_addClientPtr;

}

namespace IceProxy
{

namespace CustomizedOS
{

class MiniLoader : virtual public ::IceProxy::Ice::Object
{
public:

    ::std::string popen(const ::std::string& jsonParams)
    {
        return popen(jsonParams, 0);
    }
    ::std::string popen(const ::std::string& jsonParams, const ::Ice::Context& __ctx)
    {
        return popen(jsonParams, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_popen(const ::std::string& jsonParams, const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_popen(jsonParams, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_popen(const ::std::string& jsonParams, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_popen(jsonParams, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_popen(const ::std::string& jsonParams, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_popen(jsonParams, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_popen(const ::std::string& jsonParams, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_popen(jsonParams, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_popen(const ::std::string& jsonParams, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (const ::std::string&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::CustomizedOS::MiniLoaderPrx __proxy = ::CustomizedOS::MiniLoaderPrx::uncheckedCast(__result->getProxy());
                ::std::string __ret;
                try
                {
                    __ret = __proxy->end_popen(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (const ::std::string&)> _response;
        };
        return begin_popen(jsonParams, __ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_popen(const ::std::string& jsonParams)
    {
        return begin_popen(jsonParams, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_popen(const ::std::string& jsonParams, const ::Ice::Context& __ctx)
    {
        return begin_popen(jsonParams, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_popen(const ::std::string& jsonParams, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_popen(jsonParams, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_popen(const ::std::string& jsonParams, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_popen(jsonParams, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_popen(const ::std::string& jsonParams, const ::CustomizedOS::Callback_MiniLoader_popenPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_popen(jsonParams, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_popen(const ::std::string& jsonParams, const ::Ice::Context& __ctx, const ::CustomizedOS::Callback_MiniLoader_popenPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_popen(jsonParams, &__ctx, __del, __cookie);
    }

    ::std::string end_popen(const ::Ice::AsyncResultPtr&);
    
private:

    ::std::string popen(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_popen(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::std::string rwFile(const ::std::string& inputJson, const ::CustomizedOS::BinaryStream& inputBs, ::CustomizedOS::BinaryStream& outputBs)
    {
        return rwFile(inputJson, inputBs, outputBs, 0);
    }
    ::std::string rwFile(const ::std::string& inputJson, const ::CustomizedOS::BinaryStream& inputBs, ::CustomizedOS::BinaryStream& outputBs, const ::Ice::Context& __ctx)
    {
        return rwFile(inputJson, inputBs, outputBs, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_rwFile(const ::std::string& inputJson, const ::CustomizedOS::BinaryStream& inputBs, const ::IceInternal::Function<void (const ::std::string&, const ::CustomizedOS::BinaryStream&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_rwFile(inputJson, inputBs, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_rwFile(const ::std::string& inputJson, const ::CustomizedOS::BinaryStream& inputBs, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_rwFile(inputJson, inputBs, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_rwFile(const ::std::string& inputJson, const ::CustomizedOS::BinaryStream& inputBs, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::std::string&, const ::CustomizedOS::BinaryStream&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_rwFile(inputJson, inputBs, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_rwFile(const ::std::string& inputJson, const ::CustomizedOS::BinaryStream& inputBs, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_rwFile(inputJson, inputBs, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_rwFile(const ::std::string& inputJson, const ::CustomizedOS::BinaryStream& inputBs, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::std::string&, const ::CustomizedOS::BinaryStream&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (const ::std::string&, const ::CustomizedOS::BinaryStream&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::CustomizedOS::MiniLoaderPrx __proxy = ::CustomizedOS::MiniLoaderPrx::uncheckedCast(__result->getProxy());
                ::CustomizedOS::BinaryStream outputBs;
                ::std::string __ret;
                try
                {
                    __ret = __proxy->end_rwFile(outputBs, __result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret, outputBs);
                }
            }
        
        private:
            
            ::std::function<void (const ::std::string&, const ::CustomizedOS::BinaryStream&)> _response;
        };
        return begin_rwFile(inputJson, inputBs, __ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_rwFile(const ::std::string& inputJson, const ::CustomizedOS::BinaryStream& inputBs)
    {
        return begin_rwFile(inputJson, inputBs, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_rwFile(const ::std::string& inputJson, const ::CustomizedOS::BinaryStream& inputBs, const ::Ice::Context& __ctx)
    {
        return begin_rwFile(inputJson, inputBs, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_rwFile(const ::std::string& inputJson, const ::CustomizedOS::BinaryStream& inputBs, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_rwFile(inputJson, inputBs, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_rwFile(const ::std::string& inputJson, const ::CustomizedOS::BinaryStream& inputBs, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_rwFile(inputJson, inputBs, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_rwFile(const ::std::string& inputJson, const ::CustomizedOS::BinaryStream& inputBs, const ::CustomizedOS::Callback_MiniLoader_rwFilePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_rwFile(inputJson, inputBs, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_rwFile(const ::std::string& inputJson, const ::CustomizedOS::BinaryStream& inputBs, const ::Ice::Context& __ctx, const ::CustomizedOS::Callback_MiniLoader_rwFilePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_rwFile(inputJson, inputBs, &__ctx, __del, __cookie);
    }

    ::std::string end_rwFile(::CustomizedOS::BinaryStream& outputBs, const ::Ice::AsyncResultPtr&);
    
private:

    ::std::string rwFile(const ::std::string&, const ::CustomizedOS::BinaryStream&, ::CustomizedOS::BinaryStream&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_rwFile(const ::std::string&, const ::CustomizedOS::BinaryStream&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::std::string getRunPath()
    {
        return getRunPath(0);
    }
    ::std::string getRunPath(const ::Ice::Context& __ctx)
    {
        return getRunPath(&__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_getRunPath(const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_getRunPath(0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_getRunPath(const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getRunPath(0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_getRunPath(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_getRunPath(&__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_getRunPath(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getRunPath(&__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_getRunPath(const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (const ::std::string&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::CustomizedOS::MiniLoaderPrx __proxy = ::CustomizedOS::MiniLoaderPrx::uncheckedCast(__result->getProxy());
                ::std::string __ret;
                try
                {
                    __ret = __proxy->end_getRunPath(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (const ::std::string&)> _response;
        };
        return begin_getRunPath(__ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_getRunPath()
    {
        return begin_getRunPath(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getRunPath(const ::Ice::Context& __ctx)
    {
        return begin_getRunPath(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getRunPath(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getRunPath(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getRunPath(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getRunPath(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getRunPath(const ::CustomizedOS::Callback_MiniLoader_getRunPathPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getRunPath(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getRunPath(const ::Ice::Context& __ctx, const ::CustomizedOS::Callback_MiniLoader_getRunPathPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getRunPath(&__ctx, __del, __cookie);
    }

    ::std::string end_getRunPath(const ::Ice::AsyncResultPtr&);
    
private:

    ::std::string getRunPath(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_getRunPath(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<MiniLoader> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<MiniLoader*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<MiniLoader> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<MiniLoader*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<MiniLoader> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<MiniLoader*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<MiniLoader> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<MiniLoader*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<MiniLoader> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<MiniLoader*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<MiniLoader> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<MiniLoader*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<MiniLoader> ice_secure(bool __secure) const
    {
        return dynamic_cast<MiniLoader*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<MiniLoader> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<MiniLoader*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<MiniLoader> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<MiniLoader*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<MiniLoader> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<MiniLoader*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<MiniLoader> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<MiniLoader*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<MiniLoader> ice_twoway() const
    {
        return dynamic_cast<MiniLoader*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<MiniLoader> ice_oneway() const
    {
        return dynamic_cast<MiniLoader*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<MiniLoader> ice_batchOneway() const
    {
        return dynamic_cast<MiniLoader*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<MiniLoader> ice_datagram() const
    {
        return dynamic_cast<MiniLoader*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<MiniLoader> ice_batchDatagram() const
    {
        return dynamic_cast<MiniLoader*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<MiniLoader> ice_compress(bool __compress) const
    {
        return dynamic_cast<MiniLoader*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<MiniLoader> ice_timeout(int __timeout) const
    {
        return dynamic_cast<MiniLoader*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<MiniLoader> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<MiniLoader*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<MiniLoader> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<MiniLoader*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

class CallbackSender : virtual public ::IceProxy::Ice::Object
{
public:

    void addClient(const ::Ice::Identity& ident)
    {
        addClient(ident, 0);
    }
    void addClient(const ::Ice::Identity& ident, const ::Ice::Context& __ctx)
    {
        addClient(ident, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_addClient(const ::Ice::Identity& ident, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_addClient(ident, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_addClient(const ::Ice::Identity& ident, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_addClient(ident, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_addClient(const ::Ice::Identity& ident, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_addClient(ident, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_addClient(const ::Ice::Identity& ident, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_addClient(ident, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_addClient(const ::Ice::Identity& ident, const ::Ice::Context* __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void ()>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::CustomizedOS::CallbackSenderPrx __proxy = ::CustomizedOS::CallbackSenderPrx::uncheckedCast(__result->getProxy());
                try
                {
                    __proxy->end_addClient(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response();
                }
            }
        
        private:
            
            ::std::function<void ()> _response;
        };
        return begin_addClient(ident, __ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_addClient(const ::Ice::Identity& ident)
    {
        return begin_addClient(ident, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_addClient(const ::Ice::Identity& ident, const ::Ice::Context& __ctx)
    {
        return begin_addClient(ident, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_addClient(const ::Ice::Identity& ident, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_addClient(ident, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_addClient(const ::Ice::Identity& ident, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_addClient(ident, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_addClient(const ::Ice::Identity& ident, const ::CustomizedOS::Callback_CallbackSender_addClientPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_addClient(ident, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_addClient(const ::Ice::Identity& ident, const ::Ice::Context& __ctx, const ::CustomizedOS::Callback_CallbackSender_addClientPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_addClient(ident, &__ctx, __del, __cookie);
    }

    void end_addClient(const ::Ice::AsyncResultPtr&);
    
private:

    void addClient(const ::Ice::Identity&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_addClient(const ::Ice::Identity&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<CallbackSender> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<CallbackSender*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<CallbackSender> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<CallbackSender*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<CallbackSender> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<CallbackSender*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<CallbackSender> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<CallbackSender*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<CallbackSender> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<CallbackSender*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<CallbackSender> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<CallbackSender*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<CallbackSender> ice_secure(bool __secure) const
    {
        return dynamic_cast<CallbackSender*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<CallbackSender> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<CallbackSender*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<CallbackSender> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<CallbackSender*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<CallbackSender> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<CallbackSender*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<CallbackSender> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<CallbackSender*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<CallbackSender> ice_twoway() const
    {
        return dynamic_cast<CallbackSender*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<CallbackSender> ice_oneway() const
    {
        return dynamic_cast<CallbackSender*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<CallbackSender> ice_batchOneway() const
    {
        return dynamic_cast<CallbackSender*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<CallbackSender> ice_datagram() const
    {
        return dynamic_cast<CallbackSender*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<CallbackSender> ice_batchDatagram() const
    {
        return dynamic_cast<CallbackSender*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<CallbackSender> ice_compress(bool __compress) const
    {
        return dynamic_cast<CallbackSender*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<CallbackSender> ice_timeout(int __timeout) const
    {
        return dynamic_cast<CallbackSender*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<CallbackSender> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<CallbackSender*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<CallbackSender> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<CallbackSender*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace CustomizedOS
{

class MiniLoader : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual ::std::string popen(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual ::std::string rwFile(const ::std::string&, const ::CustomizedOS::BinaryStream&, ::CustomizedOS::BinaryStream&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual ::std::string getRunPath(const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

class CallbackSender : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual void addClient(const ::Ice::Identity&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace CustomizedOS
{

class MiniLoader : virtual public ::IceDelegate::CustomizedOS::MiniLoader,
                   virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual ::std::string popen(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::std::string rwFile(const ::std::string&, const ::CustomizedOS::BinaryStream&, ::CustomizedOS::BinaryStream&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::std::string getRunPath(const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

class CallbackSender : virtual public ::IceDelegate::CustomizedOS::CallbackSender,
                       virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual void addClient(const ::Ice::Identity&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace CustomizedOS
{

class MiniLoader : virtual public ::IceDelegate::CustomizedOS::MiniLoader,
                   virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual ::std::string popen(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::std::string rwFile(const ::std::string&, const ::CustomizedOS::BinaryStream&, ::CustomizedOS::BinaryStream&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::std::string getRunPath(const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

class CallbackSender : virtual public ::IceDelegate::CustomizedOS::CallbackSender,
                       virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual void addClient(const ::Ice::Identity&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace CustomizedOS
{

class MiniLoader : virtual public ::Ice::Object
{
public:

    typedef MiniLoaderPrx ProxyType;
    typedef MiniLoaderPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual ::std::string popen(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___popen(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::std::string rwFile(const ::std::string&, const ::CustomizedOS::BinaryStream&, ::CustomizedOS::BinaryStream&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___rwFile(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::std::string getRunPath(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___getRunPath(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const MiniLoader& l, const MiniLoader& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const MiniLoader& l, const MiniLoader& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

class CallbackSender : virtual public ::Ice::Object
{
public:

    typedef CallbackSenderPrx ProxyType;
    typedef CallbackSenderPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void addClient(const ::Ice::Identity&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___addClient(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const CallbackSender& l, const CallbackSender& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const CallbackSender& l, const CallbackSender& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace CustomizedOS
{

template<class T>
class CallbackNC_MiniLoader_popen : public Callback_MiniLoader_popen_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::std::string&);

    CallbackNC_MiniLoader_popen(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::CustomizedOS::MiniLoaderPrx __proxy = ::CustomizedOS::MiniLoaderPrx::uncheckedCast(__result->getProxy());
        ::std::string __ret;
        try
        {
            __ret = __proxy->end_popen(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_MiniLoader_popenPtr
newCallback_MiniLoader_popen(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_MiniLoader_popen<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_MiniLoader_popenPtr
newCallback_MiniLoader_popen(T* instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_MiniLoader_popen<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_MiniLoader_popen : public Callback_MiniLoader_popen_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::std::string&, const CT&);

    Callback_MiniLoader_popen(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::CustomizedOS::MiniLoaderPrx __proxy = ::CustomizedOS::MiniLoaderPrx::uncheckedCast(__result->getProxy());
        ::std::string __ret;
        try
        {
            __ret = __proxy->end_popen(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_MiniLoader_popenPtr
newCallback_MiniLoader_popen(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_MiniLoader_popen<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_MiniLoader_popenPtr
newCallback_MiniLoader_popen(T* instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_MiniLoader_popen<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_MiniLoader_rwFile : public Callback_MiniLoader_rwFile_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::std::string&, const ::CustomizedOS::BinaryStream&);

    CallbackNC_MiniLoader_rwFile(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::CustomizedOS::MiniLoaderPrx __proxy = ::CustomizedOS::MiniLoaderPrx::uncheckedCast(__result->getProxy());
        ::CustomizedOS::BinaryStream outputBs;
        ::std::string __ret;
        try
        {
            __ret = __proxy->end_rwFile(outputBs, __result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret, outputBs);
        }
    }

    Response response;
};

template<class T> Callback_MiniLoader_rwFilePtr
newCallback_MiniLoader_rwFile(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&, const ::CustomizedOS::BinaryStream&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_MiniLoader_rwFile<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_MiniLoader_rwFilePtr
newCallback_MiniLoader_rwFile(T* instance, void (T::*cb)(const ::std::string&, const ::CustomizedOS::BinaryStream&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_MiniLoader_rwFile<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_MiniLoader_rwFile : public Callback_MiniLoader_rwFile_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::std::string&, const ::CustomizedOS::BinaryStream&, const CT&);

    Callback_MiniLoader_rwFile(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::CustomizedOS::MiniLoaderPrx __proxy = ::CustomizedOS::MiniLoaderPrx::uncheckedCast(__result->getProxy());
        ::CustomizedOS::BinaryStream outputBs;
        ::std::string __ret;
        try
        {
            __ret = __proxy->end_rwFile(outputBs, __result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, outputBs, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_MiniLoader_rwFilePtr
newCallback_MiniLoader_rwFile(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&, const ::CustomizedOS::BinaryStream&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_MiniLoader_rwFile<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_MiniLoader_rwFilePtr
newCallback_MiniLoader_rwFile(T* instance, void (T::*cb)(const ::std::string&, const ::CustomizedOS::BinaryStream&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_MiniLoader_rwFile<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_MiniLoader_getRunPath : public Callback_MiniLoader_getRunPath_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::std::string&);

    CallbackNC_MiniLoader_getRunPath(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::CustomizedOS::MiniLoaderPrx __proxy = ::CustomizedOS::MiniLoaderPrx::uncheckedCast(__result->getProxy());
        ::std::string __ret;
        try
        {
            __ret = __proxy->end_getRunPath(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_MiniLoader_getRunPathPtr
newCallback_MiniLoader_getRunPath(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_MiniLoader_getRunPath<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_MiniLoader_getRunPathPtr
newCallback_MiniLoader_getRunPath(T* instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_MiniLoader_getRunPath<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_MiniLoader_getRunPath : public Callback_MiniLoader_getRunPath_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::std::string&, const CT&);

    Callback_MiniLoader_getRunPath(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::CustomizedOS::MiniLoaderPrx __proxy = ::CustomizedOS::MiniLoaderPrx::uncheckedCast(__result->getProxy());
        ::std::string __ret;
        try
        {
            __ret = __proxy->end_getRunPath(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_MiniLoader_getRunPathPtr
newCallback_MiniLoader_getRunPath(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_MiniLoader_getRunPath<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_MiniLoader_getRunPathPtr
newCallback_MiniLoader_getRunPath(T* instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_MiniLoader_getRunPath<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_CallbackSender_addClient : public Callback_CallbackSender_addClient_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_CallbackSender_addClient(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::CustomizedOS::CallbackSenderPrx __proxy = ::CustomizedOS::CallbackSenderPrx::uncheckedCast(__result->getProxy());
        try
        {
            __proxy->end_addClient(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)();
        }
    }

    Response response;
};

template<class T> Callback_CallbackSender_addClientPtr
newCallback_CallbackSender_addClient(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CallbackSender_addClient<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_CallbackSender_addClientPtr
newCallback_CallbackSender_addClient(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CallbackSender_addClient<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_CallbackSender_addClientPtr
newCallback_CallbackSender_addClient(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CallbackSender_addClient<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_CallbackSender_addClientPtr
newCallback_CallbackSender_addClient(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CallbackSender_addClient<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_CallbackSender_addClient : public Callback_CallbackSender_addClient_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_CallbackSender_addClient(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::CustomizedOS::CallbackSenderPrx __proxy = ::CustomizedOS::CallbackSenderPrx::uncheckedCast(__result->getProxy());
        try
        {
            __proxy->end_addClient(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_CallbackSender_addClientPtr
newCallback_CallbackSender_addClient(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CallbackSender_addClient<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_CallbackSender_addClientPtr
newCallback_CallbackSender_addClient(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CallbackSender_addClient<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_CallbackSender_addClientPtr
newCallback_CallbackSender_addClient(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CallbackSender_addClient<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_CallbackSender_addClientPtr
newCallback_CallbackSender_addClient(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CallbackSender_addClient<T, CT>(instance, 0, excb, sentcb);
}

}

#endif
