// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `utils.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef ____cpp_3_5_utils_h__
#define ____cpp_3_5_utils_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace Utils
{

class Callable;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::Utils::Callable>&);
::IceProxy::Ice::Object* upCast(::IceProxy::Utils::Callable*);

}

}

namespace Utils
{

class Callable;
bool operator==(const Callable&, const Callable&);
bool operator<(const Callable&, const Callable&);
::Ice::Object* upCast(::Utils::Callable*);
typedef ::IceInternal::Handle< ::Utils::Callable> CallablePtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::Utils::Callable> CallablePrx;
void __patch(CallablePtr&, const ::Ice::ObjectPtr&);

}

namespace Utils
{

class ErrorBase : public ::Ice::UserException
{
public:

    ErrorBase() {}
    ErrorBase(const ::std::string&, const ::std::string&);
    virtual ~ErrorBase() throw();

    virtual ::std::string ice_name() const;
    virtual ErrorBase* ice_clone() const;
    virtual void ice_throw() const;

    ::std::string description;
    ::std::string debug;

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::UserException::__writeImpl;
    using ::Ice::UserException::__readImpl;
    #endif
};

static ErrorBase __ErrorBase_init;

class SystemError : public ::Utils::ErrorBase
{
public:

    SystemError() {}
    SystemError(const ::std::string&, const ::std::string&, ::Ice::Long);
    virtual ~SystemError() throw();

    virtual ::std::string ice_name() const;
    virtual SystemError* ice_clone() const;
    virtual void ice_throw() const;

    ::Ice::Long rawCode;

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Utils::ErrorBase::__writeImpl;
    using ::Utils::ErrorBase::__readImpl;
    #endif
};

class NeedRetryLaterError : public ::Utils::ErrorBase
{
public:

    NeedRetryLaterError() {}
    NeedRetryLaterError(const ::std::string&, const ::std::string&);
    virtual ~NeedRetryLaterError() throw();

    virtual ::std::string ice_name() const;
    virtual NeedRetryLaterError* ice_clone() const;
    virtual void ice_throw() const;

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Utils::ErrorBase::__writeImpl;
    using ::Utils::ErrorBase::__readImpl;
    #endif
};

class CreateSnapshotImageError : public ::Utils::SystemError
{
public:

    CreateSnapshotImageError() {}
    CreateSnapshotImageError(const ::std::string&, const ::std::string&, ::Ice::Long);
    virtual ~CreateSnapshotImageError() throw();

    virtual ::std::string ice_name() const;
    virtual CreateSnapshotImageError* ice_clone() const;
    virtual void ice_throw() const;

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Utils::SystemError::__writeImpl;
    using ::Utils::SystemError::__readImpl;
    #endif
};

class OperationNotExistError : public ::Utils::ErrorBase
{
public:

    OperationNotExistError() {}
    OperationNotExistError(const ::std::string&, const ::std::string&);
    virtual ~OperationNotExistError() throw();

    virtual ::std::string ice_name() const;
    virtual OperationNotExistError* ice_clone() const;
    virtual void ice_throw() const;

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Utils::ErrorBase::__writeImpl;
    using ::Utils::ErrorBase::__readImpl;
    #endif
};

typedef ::std::vector< ::Ice::Byte> BinaryStream;

}

namespace Ice
{
template<>
struct StreamableTraits< ::Utils::ErrorBase>
{
    static const StreamHelperCategory helper = StreamHelperCategoryUserException;
};

template<>
struct StreamableTraits< ::Utils::SystemError>
{
    static const StreamHelperCategory helper = StreamHelperCategoryUserException;
};

template<>
struct StreamableTraits< ::Utils::NeedRetryLaterError>
{
    static const StreamHelperCategory helper = StreamHelperCategoryUserException;
};

template<>
struct StreamableTraits< ::Utils::CreateSnapshotImageError>
{
    static const StreamHelperCategory helper = StreamHelperCategoryUserException;
};

template<>
struct StreamableTraits< ::Utils::OperationNotExistError>
{
    static const StreamHelperCategory helper = StreamHelperCategoryUserException;
};

}

namespace Utils
{

class Callback_Callable_execute_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Callable_execute_Base> Callback_Callable_executePtr;

}

namespace IceProxy
{

namespace Utils
{

class Callable : virtual public ::IceProxy::Ice::Object
{
public:

    void execute(const ::std::string& callJson, const ::std::string& inputJson, const ::Utils::BinaryStream& inputBs, ::std::string& outputJson, ::Utils::BinaryStream& outputBs)
    {
        execute(callJson, inputJson, inputBs, outputJson, outputBs, 0);
    }
    void execute(const ::std::string& callJson, const ::std::string& inputJson, const ::Utils::BinaryStream& inputBs, ::std::string& outputJson, ::Utils::BinaryStream& outputBs, const ::Ice::Context& __ctx)
    {
        execute(callJson, inputJson, inputBs, outputJson, outputBs, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_execute(const ::std::string& callJson, const ::std::string& inputJson, const ::Utils::BinaryStream& inputBs, const ::IceInternal::Function<void (const ::std::string&, const ::Utils::BinaryStream&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_execute(callJson, inputJson, inputBs, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_execute(const ::std::string& callJson, const ::std::string& inputJson, const ::Utils::BinaryStream& inputBs, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_execute(callJson, inputJson, inputBs, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_execute(const ::std::string& callJson, const ::std::string& inputJson, const ::Utils::BinaryStream& inputBs, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::std::string&, const ::Utils::BinaryStream&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_execute(callJson, inputJson, inputBs, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_execute(const ::std::string& callJson, const ::std::string& inputJson, const ::Utils::BinaryStream& inputBs, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_execute(callJson, inputJson, inputBs, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_execute(const ::std::string& callJson, const ::std::string& inputJson, const ::Utils::BinaryStream& inputBs, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::std::string&, const ::Utils::BinaryStream&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (const ::std::string&, const ::Utils::BinaryStream&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::Utils::CallablePrx __proxy = ::Utils::CallablePrx::uncheckedCast(__result->getProxy());
                ::std::string outputJson;
                ::Utils::BinaryStream outputBs;
                try
                {
                    __proxy->end_execute(outputJson, outputBs, __result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(outputJson, outputBs);
                }
            }
        
        private:
            
            ::std::function<void (const ::std::string&, const ::Utils::BinaryStream&)> _response;
        };
        return begin_execute(callJson, inputJson, inputBs, __ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_execute(const ::std::string& callJson, const ::std::string& inputJson, const ::Utils::BinaryStream& inputBs)
    {
        return begin_execute(callJson, inputJson, inputBs, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_execute(const ::std::string& callJson, const ::std::string& inputJson, const ::Utils::BinaryStream& inputBs, const ::Ice::Context& __ctx)
    {
        return begin_execute(callJson, inputJson, inputBs, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_execute(const ::std::string& callJson, const ::std::string& inputJson, const ::Utils::BinaryStream& inputBs, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_execute(callJson, inputJson, inputBs, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_execute(const ::std::string& callJson, const ::std::string& inputJson, const ::Utils::BinaryStream& inputBs, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_execute(callJson, inputJson, inputBs, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_execute(const ::std::string& callJson, const ::std::string& inputJson, const ::Utils::BinaryStream& inputBs, const ::Utils::Callback_Callable_executePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_execute(callJson, inputJson, inputBs, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_execute(const ::std::string& callJson, const ::std::string& inputJson, const ::Utils::BinaryStream& inputBs, const ::Ice::Context& __ctx, const ::Utils::Callback_Callable_executePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_execute(callJson, inputJson, inputBs, &__ctx, __del, __cookie);
    }

    void end_execute(::std::string& outputJson, ::Utils::BinaryStream& outputBs, const ::Ice::AsyncResultPtr&);
    
private:

    void execute(const ::std::string&, const ::std::string&, const ::Utils::BinaryStream&, ::std::string&, ::Utils::BinaryStream&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_execute(const ::std::string&, const ::std::string&, const ::Utils::BinaryStream&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<Callable> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<Callable*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<Callable> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<Callable*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<Callable> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<Callable*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<Callable> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<Callable*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Callable> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<Callable*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<Callable> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<Callable*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<Callable> ice_secure(bool __secure) const
    {
        return dynamic_cast<Callable*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<Callable> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<Callable*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<Callable> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<Callable*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<Callable> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<Callable*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<Callable> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<Callable*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<Callable> ice_twoway() const
    {
        return dynamic_cast<Callable*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<Callable> ice_oneway() const
    {
        return dynamic_cast<Callable*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<Callable> ice_batchOneway() const
    {
        return dynamic_cast<Callable*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<Callable> ice_datagram() const
    {
        return dynamic_cast<Callable*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<Callable> ice_batchDatagram() const
    {
        return dynamic_cast<Callable*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<Callable> ice_compress(bool __compress) const
    {
        return dynamic_cast<Callable*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<Callable> ice_timeout(int __timeout) const
    {
        return dynamic_cast<Callable*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Callable> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<Callable*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<Callable> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<Callable*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace Utils
{

class Callable : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual void execute(const ::std::string&, const ::std::string&, const ::Utils::BinaryStream&, ::std::string&, ::Utils::BinaryStream&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace Utils
{

class Callable : virtual public ::IceDelegate::Utils::Callable,
                 virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual void execute(const ::std::string&, const ::std::string&, const ::Utils::BinaryStream&, ::std::string&, ::Utils::BinaryStream&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace Utils
{

class Callable : virtual public ::IceDelegate::Utils::Callable,
                 virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual void execute(const ::std::string&, const ::std::string&, const ::Utils::BinaryStream&, ::std::string&, ::Utils::BinaryStream&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace Utils
{

class Callable : virtual public ::Ice::Object
{
public:

    typedef CallablePrx ProxyType;
    typedef CallablePtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void execute(const ::std::string&, const ::std::string&, const ::Utils::BinaryStream&, ::std::string&, ::Utils::BinaryStream&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___execute(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const Callable& l, const Callable& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const Callable& l, const Callable& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace Utils
{

template<class T>
class CallbackNC_Callable_execute : public Callback_Callable_execute_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::std::string&, const ::Utils::BinaryStream&);

    CallbackNC_Callable_execute(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Utils::CallablePrx __proxy = ::Utils::CallablePrx::uncheckedCast(__result->getProxy());
        ::std::string outputJson;
        ::Utils::BinaryStream outputBs;
        try
        {
            __proxy->end_execute(outputJson, outputBs, __result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(outputJson, outputBs);
        }
    }

    Response response;
};

template<class T> Callback_Callable_executePtr
newCallback_Callable_execute(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&, const ::Utils::BinaryStream&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Callable_execute<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Callable_executePtr
newCallback_Callable_execute(T* instance, void (T::*cb)(const ::std::string&, const ::Utils::BinaryStream&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Callable_execute<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_Callable_execute : public Callback_Callable_execute_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::std::string&, const ::Utils::BinaryStream&, const CT&);

    Callback_Callable_execute(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Utils::CallablePrx __proxy = ::Utils::CallablePrx::uncheckedCast(__result->getProxy());
        ::std::string outputJson;
        ::Utils::BinaryStream outputBs;
        try
        {
            __proxy->end_execute(outputJson, outputBs, __result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(outputJson, outputBs, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_Callable_executePtr
newCallback_Callable_execute(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&, const ::Utils::BinaryStream&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Callable_execute<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Callable_executePtr
newCallback_Callable_execute(T* instance, void (T::*cb)(const ::std::string&, const ::Utils::BinaryStream&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Callable_execute<T, CT>(instance, cb, excb, sentcb);
}

}

#endif
