// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `cproxy.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef ____cpp_cproxy_h__
#define ____cpp_cproxy_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/GCObject.h>
#include <Ice/AsyncResult.h>
#include <Ice/Incoming.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <utils.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace CProxy
{

class TunnelManager;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::CProxy::TunnelManager>&);
::IceProxy::Ice::Object* upCast(::IceProxy::CProxy::TunnelManager*);

}

}

namespace CProxy
{

class TunnelManager;
bool operator==(const TunnelManager&, const TunnelManager&);
bool operator<(const TunnelManager&, const TunnelManager&);
::Ice::Object* upCast(::CProxy::TunnelManager*);
typedef ::IceInternal::Handle< ::CProxy::TunnelManager> TunnelManagerPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::CProxy::TunnelManager> TunnelManagerPrx;
void __patch(TunnelManagerPtr&, const ::Ice::ObjectPtr&);

}

namespace CProxy
{

struct EndPoint
{
    ::Ice::Int Index;
    ::std::string IpAddress;
    ::Ice::Int Port;

    bool operator==(const EndPoint& __rhs) const
    {
        if(this == &__rhs)
        {
            return true;
        }
        if(Index != __rhs.Index)
        {
            return false;
        }
        if(IpAddress != __rhs.IpAddress)
        {
            return false;
        }
        if(Port != __rhs.Port)
        {
            return false;
        }
        return true;
    }

    bool operator<(const EndPoint& __rhs) const
    {
        if(this == &__rhs)
        {
            return false;
        }
        if(Index < __rhs.Index)
        {
            return true;
        }
        else if(__rhs.Index < Index)
        {
            return false;
        }
        if(IpAddress < __rhs.IpAddress)
        {
            return true;
        }
        else if(__rhs.IpAddress < IpAddress)
        {
            return false;
        }
        if(Port < __rhs.Port)
        {
            return true;
        }
        else if(__rhs.Port < Port)
        {
            return false;
        }
        return false;
    }

    bool operator!=(const EndPoint& __rhs) const
    {
        return !operator==(__rhs);
    }
    bool operator<=(const EndPoint& __rhs) const
    {
        return operator<(__rhs) || operator==(__rhs);
    }
    bool operator>(const EndPoint& __rhs) const
    {
        return !operator<(__rhs) && !operator==(__rhs);
    }
    bool operator>=(const EndPoint& __rhs) const
    {
        return !operator<(__rhs);
    }
};

typedef ::std::vector< ::CProxy::EndPoint> EndPoints;

}

namespace Ice
{
template<>
struct StreamableTraits< ::CProxy::EndPoint>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 9;
    static const bool fixedLength = false;
};

template<class S>
struct StreamWriter< ::CProxy::EndPoint, S>
{
    static void write(S* __os, const ::CProxy::EndPoint& v)
    {
        __os->write(v.Index);
        __os->write(v.IpAddress);
        __os->write(v.Port);
    }
};

template<class S>
struct StreamReader< ::CProxy::EndPoint, S>
{
    static void read(S* __is, ::CProxy::EndPoint& v)
    {
        __is->read(v.Index);
        __is->read(v.IpAddress);
        __is->read(v.Port);
    }
};

}

namespace CProxy
{

class Callback_TunnelManager_Update_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_TunnelManager_Update_Base> Callback_TunnelManager_UpdatePtr;

class Callback_TunnelManager_QueryIndexByInternalLinkSourcePort_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_TunnelManager_QueryIndexByInternalLinkSourcePort_Base> Callback_TunnelManager_QueryIndexByInternalLinkSourcePortPtr;

}

namespace IceProxy
{

namespace CProxy
{

class TunnelManager : virtual public ::IceProxy::Ice::Object
{
public:

    void Update(const ::CProxy::EndPoints& __p_endPoints)
    {
        Update(__p_endPoints, 0);
    }
    void Update(const ::CProxy::EndPoints& __p_endPoints, const ::Ice::Context& __ctx)
    {
        Update(__p_endPoints, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_Update(const ::CProxy::EndPoints& __p_endPoints, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_Update(__p_endPoints, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_Update(const ::CProxy::EndPoints& __p_endPoints, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_Update(__p_endPoints, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_Update(const ::CProxy::EndPoints& __p_endPoints, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_Update(__p_endPoints, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_Update(const ::CProxy::EndPoints& __p_endPoints, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_Update(__p_endPoints, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_Update(const ::CProxy::EndPoints& __p_endPoints, const ::Ice::Context* __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent);
    
public:
#endif

    ::Ice::AsyncResultPtr begin_Update(const ::CProxy::EndPoints& __p_endPoints)
    {
        return begin_Update(__p_endPoints, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_Update(const ::CProxy::EndPoints& __p_endPoints, const ::Ice::Context& __ctx)
    {
        return begin_Update(__p_endPoints, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_Update(const ::CProxy::EndPoints& __p_endPoints, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_Update(__p_endPoints, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_Update(const ::CProxy::EndPoints& __p_endPoints, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_Update(__p_endPoints, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_Update(const ::CProxy::EndPoints& __p_endPoints, const ::CProxy::Callback_TunnelManager_UpdatePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_Update(__p_endPoints, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_Update(const ::CProxy::EndPoints& __p_endPoints, const ::Ice::Context& __ctx, const ::CProxy::Callback_TunnelManager_UpdatePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_Update(__p_endPoints, &__ctx, __del, __cookie);
    }

    void end_Update(const ::Ice::AsyncResultPtr&);
    
private:

    void Update(const ::CProxy::EndPoints&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_Update(const ::CProxy::EndPoints&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::Ice::Int QueryIndexByInternalLinkSourcePort(::Ice::Int __p_port)
    {
        return QueryIndexByInternalLinkSourcePort(__p_port, 0);
    }
    ::Ice::Int QueryIndexByInternalLinkSourcePort(::Ice::Int __p_port, const ::Ice::Context& __ctx)
    {
        return QueryIndexByInternalLinkSourcePort(__p_port, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_QueryIndexByInternalLinkSourcePort(::Ice::Int __p_port, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_QueryIndexByInternalLinkSourcePort(__p_port, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_QueryIndexByInternalLinkSourcePort(::Ice::Int __p_port, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_QueryIndexByInternalLinkSourcePort(__p_port, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_QueryIndexByInternalLinkSourcePort(::Ice::Int __p_port, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_QueryIndexByInternalLinkSourcePort(__p_port, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_QueryIndexByInternalLinkSourcePort(::Ice::Int __p_port, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_QueryIndexByInternalLinkSourcePort(__p_port, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_QueryIndexByInternalLinkSourcePort(::Ice::Int __p_port, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent);
    
public:
#endif

    ::Ice::AsyncResultPtr begin_QueryIndexByInternalLinkSourcePort(::Ice::Int __p_port)
    {
        return begin_QueryIndexByInternalLinkSourcePort(__p_port, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_QueryIndexByInternalLinkSourcePort(::Ice::Int __p_port, const ::Ice::Context& __ctx)
    {
        return begin_QueryIndexByInternalLinkSourcePort(__p_port, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_QueryIndexByInternalLinkSourcePort(::Ice::Int __p_port, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_QueryIndexByInternalLinkSourcePort(__p_port, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_QueryIndexByInternalLinkSourcePort(::Ice::Int __p_port, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_QueryIndexByInternalLinkSourcePort(__p_port, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_QueryIndexByInternalLinkSourcePort(::Ice::Int __p_port, const ::CProxy::Callback_TunnelManager_QueryIndexByInternalLinkSourcePortPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_QueryIndexByInternalLinkSourcePort(__p_port, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_QueryIndexByInternalLinkSourcePort(::Ice::Int __p_port, const ::Ice::Context& __ctx, const ::CProxy::Callback_TunnelManager_QueryIndexByInternalLinkSourcePortPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_QueryIndexByInternalLinkSourcePort(__p_port, &__ctx, __del, __cookie);
    }

    ::Ice::Int end_QueryIndexByInternalLinkSourcePort(const ::Ice::AsyncResultPtr&);
    
private:

    ::Ice::Int QueryIndexByInternalLinkSourcePort(::Ice::Int, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_QueryIndexByInternalLinkSourcePort(::Ice::Int, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<TunnelManager> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<TunnelManager*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<TunnelManager> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<TunnelManager*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<TunnelManager> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<TunnelManager*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<TunnelManager> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<TunnelManager*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<TunnelManager> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<TunnelManager*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<TunnelManager> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<TunnelManager*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<TunnelManager> ice_secure(bool __secure) const
    {
        return dynamic_cast<TunnelManager*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<TunnelManager> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<TunnelManager*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<TunnelManager> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<TunnelManager*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<TunnelManager> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<TunnelManager*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<TunnelManager> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<TunnelManager*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<TunnelManager> ice_invocationTimeout(int __timeout) const
    {
        return dynamic_cast<TunnelManager*>(::IceProxy::Ice::Object::ice_invocationTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<TunnelManager> ice_twoway() const
    {
        return dynamic_cast<TunnelManager*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<TunnelManager> ice_oneway() const
    {
        return dynamic_cast<TunnelManager*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<TunnelManager> ice_batchOneway() const
    {
        return dynamic_cast<TunnelManager*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<TunnelManager> ice_datagram() const
    {
        return dynamic_cast<TunnelManager*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<TunnelManager> ice_batchDatagram() const
    {
        return dynamic_cast<TunnelManager*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<TunnelManager> ice_compress(bool __compress) const
    {
        return dynamic_cast<TunnelManager*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<TunnelManager> ice_timeout(int __timeout) const
    {
        return dynamic_cast<TunnelManager*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<TunnelManager> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<TunnelManager*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<TunnelManager> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<TunnelManager*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace CProxy
{

class TunnelManager : virtual public ::Ice::Object
{
public:

    typedef TunnelManagerPrx ProxyType;
    typedef TunnelManagerPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void Update(const ::CProxy::EndPoints&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___Update(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::Int QueryIndexByInternalLinkSourcePort(::Ice::Int, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___QueryIndexByInternalLinkSourcePort(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
};

inline bool operator==(const TunnelManager& l, const TunnelManager& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const TunnelManager& l, const TunnelManager& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace CProxy
{

template<class T>
class CallbackNC_TunnelManager_Update : public Callback_TunnelManager_Update_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_TunnelManager_Update(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::CProxy::TunnelManagerPrx __proxy = ::CProxy::TunnelManagerPrx::uncheckedCast(__result->getProxy());
        try
        {
            __proxy->end_Update(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)();
        }
    }

    private:

    Response _response;
};

template<class T> Callback_TunnelManager_UpdatePtr
newCallback_TunnelManager_Update(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_TunnelManager_Update<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_TunnelManager_UpdatePtr
newCallback_TunnelManager_Update(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_TunnelManager_Update<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_TunnelManager_UpdatePtr
newCallback_TunnelManager_Update(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_TunnelManager_Update<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_TunnelManager_UpdatePtr
newCallback_TunnelManager_Update(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_TunnelManager_Update<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_TunnelManager_Update : public Callback_TunnelManager_Update_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_TunnelManager_Update(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::CProxy::TunnelManagerPrx __proxy = ::CProxy::TunnelManagerPrx::uncheckedCast(__result->getProxy());
        try
        {
            __proxy->end_Update(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(CT::dynamicCast(__result->getCookie()));
        }
    }

    private:

    Response _response;
};

template<class T, typename CT> Callback_TunnelManager_UpdatePtr
newCallback_TunnelManager_Update(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_TunnelManager_Update<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_TunnelManager_UpdatePtr
newCallback_TunnelManager_Update(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_TunnelManager_Update<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_TunnelManager_UpdatePtr
newCallback_TunnelManager_Update(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_TunnelManager_Update<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_TunnelManager_UpdatePtr
newCallback_TunnelManager_Update(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_TunnelManager_Update<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_TunnelManager_QueryIndexByInternalLinkSourcePort : public Callback_TunnelManager_QueryIndexByInternalLinkSourcePort_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::Ice::Int);

    CallbackNC_TunnelManager_QueryIndexByInternalLinkSourcePort(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::CProxy::TunnelManagerPrx __proxy = ::CProxy::TunnelManagerPrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_QueryIndexByInternalLinkSourcePort(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(__ret);
        }
    }

    private:

    Response _response;
};

template<class T> Callback_TunnelManager_QueryIndexByInternalLinkSourcePortPtr
newCallback_TunnelManager_QueryIndexByInternalLinkSourcePort(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_TunnelManager_QueryIndexByInternalLinkSourcePort<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_TunnelManager_QueryIndexByInternalLinkSourcePortPtr
newCallback_TunnelManager_QueryIndexByInternalLinkSourcePort(T* instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_TunnelManager_QueryIndexByInternalLinkSourcePort<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_TunnelManager_QueryIndexByInternalLinkSourcePort : public Callback_TunnelManager_QueryIndexByInternalLinkSourcePort_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::Ice::Int, const CT&);

    Callback_TunnelManager_QueryIndexByInternalLinkSourcePort(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::CProxy::TunnelManagerPrx __proxy = ::CProxy::TunnelManagerPrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_QueryIndexByInternalLinkSourcePort(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    private:

    Response _response;
};

template<class T, typename CT> Callback_TunnelManager_QueryIndexByInternalLinkSourcePortPtr
newCallback_TunnelManager_QueryIndexByInternalLinkSourcePort(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_TunnelManager_QueryIndexByInternalLinkSourcePort<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_TunnelManager_QueryIndexByInternalLinkSourcePortPtr
newCallback_TunnelManager_QueryIndexByInternalLinkSourcePort(T* instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_TunnelManager_QueryIndexByInternalLinkSourcePort<T, CT>(instance, cb, excb, sentcb);
}

}

#include <IceUtil/PopDisableWarnings.h>
#endif
