// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `install.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef ____cpp_install_h__
#define ____cpp_install_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/GCObject.h>
#include <Ice/AsyncResult.h>
#include <Ice/Incoming.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace InstallModule
{

class InstallInterface;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::InstallModule::InstallInterface>&);
::IceProxy::Ice::Object* upCast(::IceProxy::InstallModule::InstallInterface*);

}

}

namespace InstallModule
{

class InstallInterface;
bool operator==(const InstallInterface&, const InstallInterface&);
bool operator<(const InstallInterface&, const InstallInterface&);
::Ice::Object* upCast(::InstallModule::InstallInterface*);
typedef ::IceInternal::Handle< ::InstallModule::InstallInterface> InstallInterfacePtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::InstallModule::InstallInterface> InstallInterfacePrx;
void __patch(InstallInterfacePtr&, const ::Ice::ObjectPtr&);

}

namespace InstallModule
{

class Callback_InstallInterface_install_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_InstallInterface_install_Base> Callback_InstallInterface_installPtr;

}

namespace IceProxy
{

namespace InstallModule
{

class InstallInterface : virtual public ::IceProxy::Ice::Object
{
public:

    bool install(const ::std::string& __p_path)
    {
        return install(__p_path, 0);
    }
    bool install(const ::std::string& __p_path, const ::Ice::Context& __ctx)
    {
        return install(__p_path, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_install(const ::std::string& __p_path, const ::IceInternal::Function<void (bool)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_install(__p_path, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_install(const ::std::string& __p_path, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_install(__p_path, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_install(const ::std::string& __p_path, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (bool)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_install(__p_path, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_install(const ::std::string& __p_path, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_install(__p_path, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_install(const ::std::string& __p_path, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (bool)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent);
    
public:
#endif

    ::Ice::AsyncResultPtr begin_install(const ::std::string& __p_path)
    {
        return begin_install(__p_path, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_install(const ::std::string& __p_path, const ::Ice::Context& __ctx)
    {
        return begin_install(__p_path, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_install(const ::std::string& __p_path, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_install(__p_path, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_install(const ::std::string& __p_path, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_install(__p_path, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_install(const ::std::string& __p_path, const ::InstallModule::Callback_InstallInterface_installPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_install(__p_path, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_install(const ::std::string& __p_path, const ::Ice::Context& __ctx, const ::InstallModule::Callback_InstallInterface_installPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_install(__p_path, &__ctx, __del, __cookie);
    }

    bool end_install(const ::Ice::AsyncResultPtr&);
    
private:

    bool install(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_install(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<InstallInterface> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<InstallInterface*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<InstallInterface> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<InstallInterface*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<InstallInterface> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<InstallInterface*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<InstallInterface> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<InstallInterface*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<InstallInterface> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<InstallInterface*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<InstallInterface> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<InstallInterface*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<InstallInterface> ice_secure(bool __secure) const
    {
        return dynamic_cast<InstallInterface*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<InstallInterface> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<InstallInterface*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<InstallInterface> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<InstallInterface*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<InstallInterface> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<InstallInterface*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<InstallInterface> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<InstallInterface*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<InstallInterface> ice_invocationTimeout(int __timeout) const
    {
        return dynamic_cast<InstallInterface*>(::IceProxy::Ice::Object::ice_invocationTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<InstallInterface> ice_twoway() const
    {
        return dynamic_cast<InstallInterface*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<InstallInterface> ice_oneway() const
    {
        return dynamic_cast<InstallInterface*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<InstallInterface> ice_batchOneway() const
    {
        return dynamic_cast<InstallInterface*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<InstallInterface> ice_datagram() const
    {
        return dynamic_cast<InstallInterface*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<InstallInterface> ice_batchDatagram() const
    {
        return dynamic_cast<InstallInterface*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<InstallInterface> ice_compress(bool __compress) const
    {
        return dynamic_cast<InstallInterface*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<InstallInterface> ice_timeout(int __timeout) const
    {
        return dynamic_cast<InstallInterface*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<InstallInterface> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<InstallInterface*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<InstallInterface> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<InstallInterface*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace InstallModule
{

class InstallInterface : virtual public ::Ice::Object
{
public:

    typedef InstallInterfacePrx ProxyType;
    typedef InstallInterfacePtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual bool install(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___install(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
};

inline bool operator==(const InstallInterface& l, const InstallInterface& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const InstallInterface& l, const InstallInterface& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace InstallModule
{

template<class T>
class CallbackNC_InstallInterface_install : public Callback_InstallInterface_install_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(bool);

    CallbackNC_InstallInterface_install(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::InstallModule::InstallInterfacePrx __proxy = ::InstallModule::InstallInterfacePrx::uncheckedCast(__result->getProxy());
        bool __ret;
        try
        {
            __ret = __proxy->end_install(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(__ret);
        }
    }

    private:

    Response _response;
};

template<class T> Callback_InstallInterface_installPtr
newCallback_InstallInterface_install(const IceUtil::Handle<T>& instance, void (T::*cb)(bool), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_InstallInterface_install<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_InstallInterface_installPtr
newCallback_InstallInterface_install(T* instance, void (T::*cb)(bool), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_InstallInterface_install<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_InstallInterface_install : public Callback_InstallInterface_install_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(bool, const CT&);

    Callback_InstallInterface_install(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::InstallModule::InstallInterfacePrx __proxy = ::InstallModule::InstallInterfacePrx::uncheckedCast(__result->getProxy());
        bool __ret;
        try
        {
            __ret = __proxy->end_install(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    private:

    Response _response;
};

template<class T, typename CT> Callback_InstallInterface_installPtr
newCallback_InstallInterface_install(const IceUtil::Handle<T>& instance, void (T::*cb)(bool, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_InstallInterface_install<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_InstallInterface_installPtr
newCallback_InstallInterface_install(T* instance, void (T::*cb)(bool, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_InstallInterface_install<T, CT>(instance, cb, excb, sentcb);
}

}

#include <IceUtil/PopDisableWarnings.h>
#endif
